### ISSUE TITLE
minimum hardward requirements

### ISSUE THREAD

**Issue by emjay73** [vincentfung13/MINE#1]
Thank you for your nice work!

What if I want to run your code, do I need 48 V100 GPUs as you mentioned in the paper?

What are the minimum requirements to run this code?

Thanks in advance.

**Comment by vincentfung13** [comment]
Hi, thank you for your interest in our work. The 48 V100 GPUs setting was for training the large RealEstate10K dataset. For running the LLFF training provided in the current code and the demo, a couple of GPUs at most should do.

**Comment by lijx10** [comment]
It takes only 1 GPU, e.g., 2080ti, to run network inference and the demo we provided. You may need to tune the batch size and/or input image size if there is out-of-memory problem at inference.

**Comment by emjay73** [comment]
Thanks,
Just for information, can you briefly note the training time required for each dataset? (with number of GPUs)

**Comment by vincentfung13** [comment]
- For the LLFF dataset, it takes around a few hours with 2 GPUs;
- For the KITTI dataset, it takes approximately 1 day with 4 GPUs;
- For the Flowers Light Fields dataset, it takes 2 days with 4 GPUs.

Note that these numbers depend on the specific hyperparams you choose for your training (such as input size and the number of planes), and you might need to tune it a little bit yourself by looking at the validation results.

**Comment by emjay73** [comment]
OK, That seems doable now. 🤣 
I'll check the hyperparameters that you mentioned later.
Thank you!

**Comment by xiaoerjason** [comment]
3g的显存是不是跑不了呢T T
