### ISSUE TITLE
Training on multiple images per scene

### ISSUE THREAD

**Issue by NagabhushanSN95** [vincentfung13/MINE#16]
Hi,

I noticed in your code that there is an option to train MINE with multiple images as input. In that case, there is no scale ambiguity, right? Can you give an example of a data-loader for that case?

**Comment by vincentfung13** [comment]
Hi, 

Theoretically, it is indeed possible to make MINE take multiple images as input, so there will be no scale ambiguity if we are only training with one single scene. For multiple scenes, we will still need to align the scale of the current scene and the scale of the model output (as set here: https://github.com/vincentfung13/MINE/blob/main/configs/params_default.yaml#L26).

Hope this helps, 
Zijian

**Comment by NagabhushanSN95** [comment]
Okay, thank you!
