### ISSUE TITLE
Questions about eq(3), eq (8) and eq(12) in the paper

### ISSUE THREAD

**Issue by emjay73** [vincentfung13/MINE#5]
I have some questions about the equations in the paper.
I think those equations should be corrected.
If I misunderstood something, please let me know.

(3)
in the paper
![image](https://user-images.githubusercontent.com/36818801/136936714-21f36a4d-7817-45e6-b7c8-69fecc2235ea.png)

expected 
![image](https://user-images.githubusercontent.com/36818801/136936758-0ba633c0-becd-4fbf-a462-bfab60da0dba.png)

(8) Parenthesis position is somewhat weird.
in the paper
![image](https://user-images.githubusercontent.com/36818801/136922663-a27a8464-7349-4d50-9e6c-aaab176178c7.png)
expected
![image](https://user-images.githubusercontent.com/36818801/136922991-7476696a-7505-4ad0-8ca3-d4c1ab4ed8c0.png)

(12) Scale factor defined in MPI and MINE is in a reverse relationship, but equations do not reflect the difference.
*in the paper*
![image](https://user-images.githubusercontent.com/36818801/136923153-29d9c07c-509a-4524-82ad-8514137eebdc.png)
*expected*
![image](https://user-images.githubusercontent.com/36818801/136923765-3622ff8b-fd5b-4348-9191-7727990395f7.png)

**Comment by lijx10** [comment]
### Eq. 3
d_i = 1 / z_i. z_n is the **n**earest plane depth with smallest value, while z_f is the **farthest** plane depth with the largest value. Therefore, d_n > d_f. In Eq. 3, (d_f - d_n) < 0. So the equation is correct.

### Eq. 8
You are correct, there is a redundent left parentheses on Z_src(x,y). Thanks for pointing it out. We will update our arxiv paper.

### Eq. 12
You are correct, the predicted disparity D_src / D_tgt should be multiplied by scale s.

Thanks a lot for pointing out the errors in the paper.

**Comment by emjay73** [comment]
Oh yeah, about eq 3, I confused near/far notation with z, not disparity.
Thanks! Things get clear for me.
