### ISSUE TITLE
Qualitative comparision about KITTI

### ISSUE THREAD

**Issue by youngAt19** [vincentfung13/MINE#8]
Hi, 
there is a qualitative comparision with single-view MPI on KITTI dataset in your paper,
but I do not find their pretrained model on KITTI from their [repository](https://github.com/google-research/google-research/tree/master/single_view_mpi).
Did you train their model to get the qualitative results?
Could you provide me a copy of these qualitative results? (just for academic purposes)
Thank you.

**Comment by vincentfung13** [comment]
Hi, actually we did not re-train the MPI model, we took the original qualitative results from the MPI paper and used PhotoShop to produce the comparison. Hope this helps.

**Comment by youngAt19** [comment]
I see. Thanks :+1:
